# This file is generated by release.yml. DO NOT EDIT.
cask "gortex" do
  version "0.57.0"

  on_macos do
    on_intel do
      sha256 "72f4e7e19f2568cbb2366c06a19f0877b50c52c47799746066243b694f3d060f"
      url "https://github.com/zzet/gortex/releases/download/v#{version}/gortex_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4f0d0d1fdf5e9c7c717325a1544b671d7ab04486b6f4c657377d4cffab441feb"
      url "https://github.com/zzet/gortex/releases/download/v#{version}/gortex_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8b08b1ef6146219f96e72cb845e2ffd145e1d2a3adb8d931e065f4a933c122f1"
      url "https://github.com/zzet/gortex/releases/download/v#{version}/gortex_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ac2a193c86cec685f7fd0626836ac76af1d9349fe3b0b72e9ec36fcdd1bb217a"
      url "https://github.com/zzet/gortex/releases/download/v#{version}/gortex_linux_arm64.tar.gz"
    end
  end

  name "gortex"
  desc "Code intelligence engine that indexes repositories into an in-memory knowledge graph."
  homepage "https://github.com/zzet/gortex"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gortex"

  generate_completions_from_executable "gortex",
    shell_parameter_format: :cobra

  # No zap stanza required
end
