# This file was generated by GoReleaser. DO NOT EDIT.
cask "gortex" do
  version "0.19.0"

  on_macos do
    on_intel do
      sha256 "3bbbfe1d152de196a463bdbe75e59645285ee399b7ece3065bea6c5bc96ed991"
      url "https://github.com/zzet/gortex/releases/download/v#{version}/gortex_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "579d00b0cd50bd3426c734a29d598c7008352cd54baab1a72ff114edfd529bc3"
      url "https://github.com/zzet/gortex/releases/download/v#{version}/gortex_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f8ff05f366bc32b41cbb56e31257cc220b01b4bc575b505c13dca99ee07cb283"
      url "https://github.com/zzet/gortex/releases/download/v#{version}/gortex_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "31803b6928565604756ac2d831f3695ad7d6187184858b7526adb8d603ec2147"
      url "https://github.com/zzet/gortex/releases/download/v#{version}/gortex_linux_arm64.tar.gz"
    end
  end

  name "gortex"
  desc "Code intelligence engine that indexes repositories into an in-memory knowledge graph."
  homepage "https://github.com/zzet/gortex"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gortex"
  generate_completions_from_executable "gortex",
    shell_parameter_format: :cobra

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gortex"]
    end
  end

  # No zap stanza required

end
