# This file is generated by release.yml. DO NOT EDIT.
cask "gortex" do
  version "0.63.4"

  on_macos do
    on_intel do
      sha256 "6641c2e9126c663a2fc4873d06f43ca4895f21b656ba0ab576b656574849a79a"
      url "https://github.com/zzet/gortex/releases/download/v#{version}/gortex_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3448d311c78382a16f32c4b5d59e1cf46f9749934fbd2e63214a13eecf90ae41"
      url "https://github.com/zzet/gortex/releases/download/v#{version}/gortex_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4f5756f66eebf1ad2e6840cc570e58645bca801636dfd00f8374707eeb3bb835"
      url "https://github.com/zzet/gortex/releases/download/v#{version}/gortex_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "70607944de3bc6d62246aca45b96b35718409cb3eaff4cf2b3a479d39928053f"
      url "https://github.com/zzet/gortex/releases/download/v#{version}/gortex_linux_arm64.tar.gz"
    end
  end

  name "gortex"
  desc "Code intelligence engine that indexes repositories into an in-memory knowledge graph."
  homepage "https://github.com/zzet/gortex"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gortex"

  generate_completions_from_executable "gortex",
    shell_parameter_format: :cobra

  # No zap stanza required
end
